#!/bin/bash

touchpadID=$(xinput | grep -i touchpad | sed 's/.*id=\(.*\)\t.*/\1/')
current=$(xinput list-props $touchpadID | grep "Device Enabled" | sed 's/.*):\t\(.*\).*/\1/')

if [[ $1 == "enable" || $current == 0 ]]
	then
		xinput set-prop $touchpadID "Device Enabled" 1
	fi

if [[ $1 == "disable" || $current == 1 ]]
	then
		xinput set-prop $touchpadID "Device Enabled" 0
	fi
